export const cards = [
  {
    id: 1,
    title: "Plumber",
    desc: "Plumber Bulao",
    img: "/public/img/plumber2.jpg",
    cat: "plumber",
  },
  {
    id: 2,
    title: "Machenic",
    desc: "Machenic Bulao",
    img: "/public/img/machenic.jpg",
  },
  {
    id: 3,
    title: "Gardener",
    desc: "Mali Bulao",
    img: "/public/img/gardener.jpg",
  },
  {
    id: 4,
    title: "Electrician",
    desc: "Electrician Bulao",
    img: "/public/img/electrician.jpg",
  },
  {
    id: 5,
    title: "Carpenter",
    desc: "Tarkhaan Bulao",
    img: "/public/img/carpenter.jpg",
  },
];

export const projects = [
  {
    id: 1,
    img: "/public/img/plumber2.jpg",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Plumber",
    username: "Jilani BHai Bulao",
  },
  {
    id: 2,
    img: "/public/img/machenic.jpg",
    pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Machenic",
    username: "Jilani BHaic Bulao",
  },
  {
    id: 3,
    img: "/public/img/gardener.jpg",
    pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Gardener",
    username: "Jilani BHair Bulao",
  },
  {
    id: 4,
    img: "/public/img/electrician.jpg",
    pp: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Electrician",
    username: "Jilani BHaician Bulao",
  },
  {
    id: 5,
    img: "/public/img/carpenter.jpg",
    pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Carpenter",
    username: "Jilani BHai Bulao",
  },
];

export const gigs = [
  {
    id: 1,
    img: "/public/img/carpenter.jpg",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will make polish room doors and windows",
    price: 2000,
    star: 5,
    username: "Jilani Bhai",
  },
  {
    id: 2,
    img: "/public/img/electrician.jpg",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will do house wiring",
    price: 1500,
    star: 5,
    username: "Kabeer Bhai",
  },
  {
    id: 3,
    img: "/public/img/gardener.jpg",
    pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will plant plants",
    price: 1120,
    star: 5,
    username: "Jilani",
  },
  {
    id: 4,
    img: "/public/img/machenic.jpg",
    pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will do tunning of your car",
    price: 799,
    star: 4,
    username: "Abdur Rehman",
  },
  {
    id: 5,
    img: "/public/img/plumber2.jpg",
    pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will do senitory work",
    price: 1259,
    star: 5,
    username: "Ashraf",
  },
  {
    id: 6,
    img: "/public/img/Airconditioner.jpg",
    pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will do Ac service",
    price: 1079,
    star: 4,
    username: "Fardeen Khan",
  },
];
